= Lorenz system

This system defines a 3 dimensional trajectory by differential equations with 3 parameters.

latexmath:[
\begin{aligned}
    
    x'&=\sigma(y-x) \\
    y'&=x(r-z)-y \\
    z'&=xy-bz
    
\end{aligned}]

Here, latexmath:[x] is proportional to the rate of convection, latexmath:[y] is related to the horizontal temperature variation, and latexmath:[z] is the vertical temperature variation.

We have also three parameters all strictly positive:
* latexmath:[\sigma > 0]  relates to the Prandtl number. This number is a dimensionless quantity that puts the viscosity of a fluid in correlation with the thermal conductivity;
* latexmath:[r > 0]  relates to the Rayleigh number, it is a control parameter, representing the temperature difference between the top and bottom of the tank;
* latexmath:[b > 0] relates to the physical dimensions of the layer of fluid uniformly heated from below and cooled from above.
\end{enumerate}

We can see that this system is non-linear, because in the second differential equation ( latexmath:[\frac{dy}{dt}]) we can see the term latexmath:[xz] and in the third differential equation (latexmath:[\frac{dz}{dt}]) we have latexmath:[xy]. The three differential equations form a coupled system. 